<a href="https://colab.research.google.com/github/ashrafsohail42003/Training-project/blob/main/Feature_Engineering_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

In [ ]:
path = '/content/drive/MyDrive/AXSOSACADEMY/03-DataEnrichment/Week09/Data/bikeshare_train - bikeshare_train.csv'
df = pd.read_csv(path)
df.head()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 0:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011-01-01 1:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40
2,2011-01-01 2:00:00,1,0,0,1,9.02,13.635,80,0.0,5,27,32
3,2011-01-01 3:00:00,1,0,0,1,9.84,14.395,75,0.0,3,10,13
4,2011-01-01 4:00:00,1,0,0,1,9.84,14.395,75,0.0,0,1,1

In [4]:
df = df.drop(columns =["casual", "registered"])

In [5]:
df["datetime"] = pd.to_datetime(df["datetime"])
df["month_name"] = df["datetime"].dt.month_name().astype("object")
df["day_name"] = df["datetime"].dt.day_name().astype("object")
df["hour"] = df["datetime"].dt.hour.astype("object")
df = df.drop(columns=["datetime", "season"])
df.head()

,holiday,workingday,weather,temp,atemp,humidity,windspeed,count,month_name,day_name,hour
0,0,0,1,9.84,14.395,81,0.0,16,January,Saturday,0
1,0,0,1,9.02,13.635,80,0.0,40,January,Saturday,1
2,0,0,1,9.02,13.635,80,0.0,32,January,Saturday,2
3,0,0,1,9.84,14.395,75,0.0,13,January,Saturday,3
4,0,0,1,9.84,14.395,75,0.0,1,January,Saturday,4

In [6]:
df["temp"] = df["temp"].apply(lambda x: (x * 9/5) + 32)
df["atemp"] = df["atemp"].apply(lambda x: (x * 9/5) + 32)
df[["temp", "atemp"]].head()

     temp   atemp
0  49.712  57.911
1  48.236  56.543
2  48.236  56.543
3  49.712  57.911
4  49.712  57.911

In [7]:
df["temp_variance"] = df["temp"] - df["atemp"]

df = df.drop(columns=["atemp"])

df.head()

,holiday,workingday,weather,temp,humidity,windspeed,count,month_name,day_name,hour,temp_variance
0,0,0,1,49.712,81,0.0,16,January,Saturday,0,-8.199
1,0,0,1,48.236,80,0.0,40,January,Saturday,1,-8.307
2,0,0,1,48.236,80,0.0,32,January,Saturday,2,-8.307
3,0,0,1,49.712,75,0.0,13,January,Saturday,3,-8.199
4,0,0,1,49.712,75,0.0,1,January,Saturday,4,-8.199